apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-test
  labels:
    app: httpd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-test
  template:
    metadata:
      labels:
        app: httpd-test
    spec:
      containers:
      - name: httpd
        image: sm185402/test-httpd
        ports:
        - containerPort: 80