---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-test
  labels:
    app: httpd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-test
  template:
    metadata:
      labels:
        app: httpd-test
    spec:
      containers:
      - name: httpd
        image: sm185402/test-httpd:v1
        ports:
        - containerPort: 80
        env:
        - name: welcome
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
...
---
kind: Service
apiVersion: v1
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
...
---
apiVersion: v1
data:
  welcome: "Hello 123"
kind: ConfigMap
metadata:
  name: httpd-config
...